# Generated by Django 4.2.6 on 2023-10-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_texto', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Records',
            new_name='Record',
        ),
    ]
