# Generated by Django 4.2.6 on 2023-10-06 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_receita_autor_alter_receita_campo_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='autor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receita',
            name='campo_texto',
            field=models.TextField(),
        ),
    ]
